### ISSUE TITLE
build/chromeos_buildflags.h  file not found 

### ISSUE THREAD

**Issue by wfunny** [zh-eastsun/CrashPadDemo#1]
I actions as the md , but when I execute the command :ninja -C out/android_arm64_api21/out/Debug all,
it appears a error as follow:
ninja: Entering directory `out/android_arm64_api21/out/Debug'
[13/111] CXX obj/client/crashpad_client.crashpad_client_linux.o
FAILED: obj/client/crashpad_client.crashpad_client_linux.o 
/Users/wfunny/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++ -MMD -MF obj/client/crashpad_client.crashpad_client_linux.o.d -D_FILE_OFFSET_BITS=64 -D__ANDROID_API__=21 -DCRASHPAD_LSS_SOURCE_EMBEDDED -I../../../.. -I../../../../compat/non_mac -I../../../../compat/non_win -I../../../../compat/android -I../../../../compat/linux -I../../../../third_party/mini_chromium/mini_chromium -fPIC -fno-exceptions -fno-strict-aliasing -fstack-protector-all -fvisibility=hidden -g -pipe -pthread -Wall -Werror -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wvla -Wexit-time-destructors -Wextra-semi -Wheader-hygiene -Wimplicit-fallthrough -Wsign-compare -Wstring-conversion -O0 -fno-rtti -fvisibility-inlines-hidden -std=c++14  -c ../../../../client/crashpad_client_linux.cc -o obj/client/crashpad_client.crashpad_client_linux.o
In file included from ../../../../client/crashpad_client_linux.cc:15:
../../../../client/crashpad_client.h:28:10: fatal error: 'build/chromeos_buildflags.h' file not found
#include "build/chromeos_buildflags.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[18/111] CXX obj/util/misc/crashpad_util_test.random_string_test.o
ninja: build stopped: subcommand failed.

I do not know which step has go wrong.

**Comment by zh-eastsun** [comment]
Thanks for your report.Had you executed this command: git checkout -f 7547d0aa874f550fb3d3e8a5365ec51da96cbd86?
You must force switch to this node.I had tried to build with the latest node, but failed.
This is my crashpad_client.h file's header:
```
#include <map>
#include <set>
#include <string>
#include <vector>

#include <stdint.h>

#include "base/files/file_path.h"
#include "base/macros.h"
#include "build/build_config.h"
#include "util/file/file_io.h"
#include "util/misc/capture_context.h"

#if defined(OS_APPLE)
#include "base/mac/scoped_mach_port.h"
#elif defined(OS_WIN)
#include <windows.h>
#include "util/win/scoped_handle.h"
#elif defined(OS_LINUX) || defined(OS_ANDROID)
#include <signal.h>
#include <ucontext.h>
#endif
```
Without the #include "build/chromeos_buildflags.h".
